# Generated by Django 3.2.3 on 2023-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_subscribe_recipes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='recipes',
            field=models.ManyToManyField(related_name='subscribers', to='recipes.Recipe'),
        ),
    ]
